#!/usr/bin/env python3
"""Generate frontend/lib/errors.ts from the Python error catalog.

The Python enum is the single source of truth (section 10). Run this after
touching `app/core/errors.py`; CI fails if the checked-in file is stale.

Usage:
    python scripts/gen_error_codes.py          # write the file
    python scripts/gen_error_codes.py --check  # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.errors import ERROR_CATALOG  # noqa: E402

OUTPUT = Path(__file__).resolve().parents[2] / "frontend" / "lib" / "errors.ts"

HEADER = """// AUTO-GENERATED by backend/scripts/gen_error_codes.py -- do not edit by hand.
// Source of truth: backend/app/core/errors.py
"""


def _ts_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render() -> str:
    lines: list[str] = [HEADER, "export const ERROR_CODES = ["]
    for code in ERROR_CATALOG:
        lines.append(f"  {_ts_string(str(code))},")
    lines.append("] as const;\n")
    lines.append("export type ErrorCode = (typeof ERROR_CODES)[number];\n")
    lines.append("export interface ErrorSpec {")
    lines.append("  message: string;")
    lines.append("  action: string;")
    lines.append("  retryable: boolean;")
    lines.append("  status: number;")
    lines.append("}\n")
    lines.append("export const ERROR_CATALOG: Record<ErrorCode, ErrorSpec> = {")
    for code, spec in ERROR_CATALOG.items():
        lines.append(f"  {code}: {{")
        lines.append(f"    message: {_ts_string(spec.message)},")
        lines.append(f"    action: {_ts_string(spec.action)},")
        lines.append(f"    retryable: {str(spec.retryable).lower()},")
        lines.append(f"    status: {spec.status},")
        lines.append("  },")
    lines.append("};\n")
    lines.append(
        "export function describeError(code: string): ErrorSpec {\n"
        "  return (\n"
        "    ERROR_CATALOG[code as ErrorCode] ?? {\n"
        '      message: "Something broke on our side.",\n'
        '      action: "Try again in a moment.",\n'
        "      retryable: true,\n"
        "      status: 500,\n"
        "    }\n"
        "  );\n"
        "}\n"
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT} is out of date. Run: python scripts/gen_error_codes.py")
            return 1
        print(f"{OUTPUT} is up to date.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
