"""Pin the content of the Next.js-generated agent instruction files.

`next dev` writes `frontend/AGENTS.md` and `frontend/CLAUDE.md` (decision
D-012). They are committed deliberately: gitignoring would not remove them --
Next recreates them and agents still read them -- it would only make changes
unreviewable.

These files instruct coding agents, so a Next version bump silently rewriting
them is a change that must be *seen*. This test fails when the bytes change,
which forces the diff in front of a human. To accept a change: read the new
content, satisfy yourself it still only points at the bundled docs, then update
the digest here in the same commit.

Lives in the backend suite for the same reason `test_error_codes_sync.py` does:
it is a repository-integrity check, and this is where the test runner is.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

FRONTEND = Path(__file__).resolve().parents[2] / "frontend"

# sha256 of the block as generated by next 16.3.0.
EXPECTED = {
    "AGENTS.md": "63f2c50380ed6303237cce215ce27af1d620d094c215e28d1b1538a3c070e3bb",
    "CLAUDE.md": "336cc4fbf19beaada7ccf9986414fa91851a8d7a07dfb3ccbe800a69eed0ab49",
}

START_MARKER = "<!-- BEGIN:nextjs-agent-rules -->"
END_MARKER = "<!-- END:nextjs-agent-rules -->"

# Phrases that would signal the block had grown beyond "read the bundled docs"
# into instructing agents to reach outside the repository or run things.
SUSPICIOUS = (
    "curl",
    "wget",
    "http://",
    "npm install",
    "npx ",
    "eval",
    "token",
    "secret",
    "credential",
    "api key",
    "ignore previous",
    "disregard",
)


@pytest.mark.parametrize("filename", sorted(EXPECTED))
def test_agent_file_content_is_unchanged(filename):
    path = FRONTEND / filename
    assert path.exists(), f"{filename} is missing; next dev regenerates it"

    actual = hashlib.sha256(path.read_bytes()).hexdigest()
    assert actual == EXPECTED[filename], (
        f"\n{filename} changed.\n"
        "This file instructs coding agents, so the change needs review rather "
        "than a silent update. Read it, confirm it still only points at the "
        "bundled Next.js docs, then update the digest in this test.\n\n"
        f"--- current content ---\n{path.read_text(encoding='utf-8')}"
    )


def test_agents_md_is_only_the_managed_block():
    """Nothing has been appended outside the markers without review. Project
    instructions may legitimately go there later -- this test is what makes
    adding them a deliberate act."""
    content = (FRONTEND / "AGENTS.md").read_text(encoding="utf-8")
    assert content.count(START_MARKER) == 1
    assert content.count(END_MARKER) == 1

    before, _, rest = content.partition(START_MARKER)
    _, _, after = rest.partition(END_MARKER)
    assert before.strip() == ""
    assert after.strip() == ""


def test_claude_md_is_only_an_include():
    assert (FRONTEND / "CLAUDE.md").read_text(encoding="utf-8").strip() == "@AGENTS.md"


@pytest.mark.parametrize("filename", sorted(EXPECTED))
def test_agent_files_contain_nothing_that_reaches_outside_the_repo(filename):
    """A digest mismatch already catches any change, but this asserts the
    property we actually care about, so the failure says *why* it matters."""
    content = (FRONTEND / filename).read_text(encoding="utf-8").lower()
    for phrase in SUSPICIOUS:
        assert phrase not in content, (
            f"{filename} contains {phrase!r}. The managed block should only "
            "direct agents to the docs bundled in node_modules."
        )
