// AUTO-GENERATED by backend/scripts/gen_error_codes.py -- do not edit by hand.
// Source of truth: backend/app/core/errors.py

export const ERROR_CODES = [
  "INVALID_URL",
  "UNSUPPORTED_PLATFORM",
  "UNSUPPORTED_CONTENT_TYPE",
  "PRIVATE_CONTENT",
  "LOGIN_REQUIRED",
  "DRM_PROTECTED",
  "GEOBLOCKED",
  "CONTENT_REMOVED",
  "RATE_LIMITED",
  "EXTRACTOR_OUTDATED",
  "DURATION_EXCEEDED",
  "FILESIZE_EXCEEDED",
  "AI_UNAVAILABLE",
  "UPSTREAM_TIMEOUT",
  "INTERNAL_ERROR",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export interface ErrorSpec {
  message: string;
  action: string;
  retryable: boolean;
  status: number;
}

export const ERROR_CATALOG: Record<ErrorCode, ErrorSpec> = {
  INVALID_URL: {
    message: "That doesn't look like a valid link.",
    action: "Check the URL and paste it again, including the https:// prefix.",
    retryable: false,
    status: 400,
  },
  UNSUPPORTED_PLATFORM: {
    message: "We don't support this site.",
    action: "Supported platforms are YouTube, Instagram, Facebook, LinkedIn and Snapchat.",
    retryable: false,
    status: 400,
  },
  UNSUPPORTED_CONTENT_TYPE: {
    message: "This kind of content isn't supported on that platform yet.",
    action: "Try a direct link to a video, reel or post.",
    retryable: false,
    status: 400,
  },
  PRIVATE_CONTENT: {
    message: "This content is private.",
    action: "We only handle publicly accessible content. Ask the owner to make it public.",
    retryable: false,
    status: 403,
  },
  LOGIN_REQUIRED: {
    message: "This content requires being signed in to the platform.",
    action: "We don't sign in on your behalf. Only public content that loads in a logged-out browser can be processed.",
    retryable: false,
    status: 403,
  },
  DRM_PROTECTED: {
    message: "This stream is DRM-protected.",
    action: "We will not attempt to bypass DRM. Nothing can be downloaded from this link.",
    retryable: false,
    status: 403,
  },
  GEOBLOCKED: {
    message: "This content isn't available in the region our servers run from.",
    action: "Nothing to retry here -- the platform is blocking the request by location.",
    retryable: false,
    status: 451,
  },
  CONTENT_REMOVED: {
    message: "This content no longer exists.",
    action: "It was deleted or made unavailable by its owner.",
    retryable: false,
    status: 404,
  },
  RATE_LIMITED: {
    message: "You're going a bit fast for us.",
    action: "Wait a minute and try again.",
    retryable: true,
    status: 429,
  },
  EXTRACTOR_OUTDATED: {
    message: "This platform changed recently and we're updating support.",
    action: "This usually resolves within a day or two. Please try again later.",
    retryable: true,
    status: 503,
  },
  DURATION_EXCEEDED: {
    message: "This media is longer than the limit for that action.",
    action: "Try a shorter clip, or use a different action that has no duration cap.",
    retryable: false,
    status: 413,
  },
  FILESIZE_EXCEEDED: {
    message: "This file is larger than we can process.",
    action: "Pick a lower resolution or an audio-only format.",
    retryable: false,
    status: 413,
  },
  AI_UNAVAILABLE: {
    message: "AI features aren't enabled on this server.",
    action: "Everything except the AI tools still works normally.",
    retryable: false,
    status: 503,
  },
  UPSTREAM_TIMEOUT: {
    message: "The platform took too long to respond.",
    action: "Try again in a moment.",
    retryable: true,
    status: 504,
  },
  INTERNAL_ERROR: {
    message: "Something broke on our side.",
    action: "Try again. If it keeps happening, the request ID below helps us trace it.",
    retryable: true,
    status: 500,
  },
};

export function describeError(code: string): ErrorSpec {
  return (
    ERROR_CATALOG[code as ErrorCode] ?? {
      message: "Something broke on our side.",
      action: "Try again in a moment.",
      retryable: true,
      status: 500,
    }
  );
}
